title: P4
email: p4@p4.org
author: The P4 Language Consortium

url: "https://p4lang.github.io/p4lang"
baseurl: "/p4lang"

collections:
  events:
    output: true
    permalink: /events/:path/
    
social:
  - title: twitter
    url: https://twitter.com/p4lang
  - title: github
    url: http://github.com/p4lang

markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
include: ['_pages','_events']
exclude: ["less","node_modules","Gruntfile.js","package.json"]

plugins: [jekyll-paginate, jekyll-feed]
